name: YourWallAR Bot (v2.0 - Pexels)

on:
  schedule:
    # (جدول ذكي: "استيقظ" كل ساعة على رأس الساعة)
    - cron: '0 * * * *'

  # هذا يسمح لنا بالاختبار اليدوي
  workflow_dispatch:

jobs:
  run-wallpaper-bot:
    runs-on: ubuntu-latest
    env:
      # (المفاتيح السرية الثلاثة المطلوبة)
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }} # (تم تغيير المفتاح)
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: pip install requests pytz # (pytz للمناطق الزمنية)
        
      - name: Run Python Script (Pexels v2.0)
        run: python wallpaper_bot.py

